name: ClawK
options:
  bundleIdPrefix: ai.openclaw
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "6"
    SWIFT_STRICT_CONCURRENCY: minimal
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""

targets:
  ClawK:
    type: application
    platform: macOS
    sources:
      - path: ClawK
        excludes:
          - "**/*.entitlements"
          - "**/Info.plist"
          - "Tests/**"
          - "Resources/**"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.openclaw.clawk
        INFOPLIST_FILE: ClawK/Info.plist
        CODE_SIGN_ENTITLEMENTS: ClawK/ClawK.entitlements
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: NO
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: ClawK/ClawK.entitlements

  ClawKTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: ClawKTests
    dependencies:
      - target: ClawK
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        BUNDLE_LOADER: "$(BUILT_PRODUCTS_DIR)/ClawK.app/Contents/MacOS/ClawK"
        TEST_HOST: "$(BUNDLE_LOADER)"

schemes:
  ClawK:
    build:
      targets:
        ClawK: all
        ClawKTests: [test]
    test:
      config: Debug
      targets:
        - ClawKTests
    run:
      config: Debug
    profile:
      config: Release
    archive:
      config: Release
